### ISSUE TITLE
Textual revamp

### ISSUE THREAD

**Issue by dmoisset** [iritkatriel/codoscope#8]
Hi @iritkatriel ! As discussed in the PyConUS sprint, I've been re-implementing your codoscope using [textual](https://textual.textualize.io/) as frontend.

Here's the code:

 - https://github.com/dmoisset/codoscope

Right now it has feature parity with your original work, plus line highlighting (on hover, so you can easily map from any of the views to the other, e.g. hover on a ast node and see what are the corresponding tokens, source & bytecodes) It also has syntax highlighting, and with textual it should be easy to make the display much nicer (but I wanted to share something at this stage where it's quite usable). I also made it work in 3.12 (without showing the intermediate optimization stages, but I think it's still useful for educational purposes).

I could submit this as a large PR (which would remove all + add all the new code), but I didn't wanted to do that until you take a look and tell me that this would make sense. I wouldn't mind maintaining this in the other repo (I plan to keep working on this, and have several improvements coming up)

The code as it is would extend nicely to add panels to display specialized tier 1 bytecode, tier 2, and I would also would like to get a JIT output disassembly (machine level instructions); this would probably would be a callable entry point that allows you to launch this from running code (so the code gets a chance to be specialized/tier2-ized/jitted).

**Comment by iritkatriel** [comment]
Thanks!

I tried to install with the instructions in the readme but I think they are not quite right - can you check?

For instance, there seems to be something missing between these two lines:

```
git clone https://github.com/dmoisset/codoscope.git
../env/bin/pip install
```

**Comment by iritkatriel** [comment]
Ah, if I just skip the "../env/bin/pip install" line then I think it works.

**Comment by iritkatriel** [comment]
Yes, I got it working. I like it, let's go for this.

**Comment by dmoisset** [comment]
Ok, I'll prepare the PR

**Comment by dmoisset** [comment]
> Ah, if I just skip the "../env/bin/pip install" line then I think it works.

removed this

**Comment by dmoisset** [comment]
Should we close this issue?

**Comment by sylvainmouquet** [comment]
it's a great tool.
It could be good to have a vscode extension to display the code, the ast, the bytecode, ... in the same place

**Comment by iritkatriel** [comment]
@sylvainmouquet inseed. Could you create a new issue to discuss that?
